blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/JosefNGS/LADEMO/discussions
    about: Ask questions and discuss ideas
  - name: ðŸ“š Documentation
    url: https://github.com/JosefNGS/LADEMO#readme
    about: Check the documentation
  - name: ðŸ”’ Security
    url: https://github.com/JosefNGS/LADEMO/security
    about: Report a security vulnerability

